version: '3.8'

services:
  k8helper:
    build: .
    ports:
      - "8080:8080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ${KUBECONFIG:-~/.kube/config}:/root/.kube/config:ro
      - ./config.yml:/app/config.yml:ro
    restart: unless-stopped 