apiVersion: v1
kind: Secret
metadata:
  name: k8helper-secrets
type: Opaque
data:
  tencent-secret-id: {{ .Values.secrets.tencentSecretId | b64enc }}
  tencent-secret-key: {{ .Values.secrets.tencentSecretKey | b64enc }}
  hunyuan-api-key: {{ .Values.secrets.hunyuanApiKey | b64enc }}
  hunyuan-secret-key: {{ .Values.secrets.hunyuanSecretKey | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: k8helper-kubeconfig
type: Opaque
data:
  config: {{ .Values.secrets.kubeConfig | b64enc }} 