apiVersion: v1
kind: Secret
metadata:
  name: k8helper-secrets
type: Opaque
data:
  hunyuan-api-key: {{ .Values.secrets.hunyuanApiKey | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: k8helper-kubeconfig
type: Opaque
data:
  config: {{ .Values.secrets.kubeConfig | b64enc }} 