apiVersion: v1
kind: Service
metadata:
  name: k8helper
  labels:
    app: k8helper
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: k8helper 